// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDerV8xWwtf-6tzrqIMIc7Cxt_LuTwCtc8',
    appId: '1:446815211035:web:5326bdddec0853319d72be',
    messagingSenderId: '446815211035',
    projectId: 'webportal-73955',
    authDomain: 'webportal-73955.firebaseapp.com',
    storageBucket: 'webportal-73955.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk53XeltOAR4UPlehl_CfgwIf54NvS-mg',
    appId: '1:446815211035:android:e6e7d87a002601f19d72be',
    messagingSenderId: '446815211035',
    projectId: 'webportal-73955',
    storageBucket: 'webportal-73955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7-DNSmCSHEa-8QbAvfFlH-hgCgJXPAoA',
    appId: '1:446815211035:ios:254d35590a5f65b99d72be',
    messagingSenderId: '446815211035',
    projectId: 'webportal-73955',
    storageBucket: 'webportal-73955.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7-DNSmCSHEa-8QbAvfFlH-hgCgJXPAoA',
    appId: '1:446815211035:ios:254d35590a5f65b99d72be',
    messagingSenderId: '446815211035',
    projectId: 'webportal-73955',
    storageBucket: 'webportal-73955.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDerV8xWwtf-6tzrqIMIc7Cxt_LuTwCtc8',
    appId: '1:446815211035:web:bcc3a2cfd09ba6e49d72be',
    messagingSenderId: '446815211035',
    projectId: 'webportal-73955',
    authDomain: 'webportal-73955.firebaseapp.com',
    storageBucket: 'webportal-73955.appspot.com',
  );

}